# -*- coding: utf-8 -*-
"""Assignment 02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1beHVwqj-uR4FElRt3NX7Bm3xXvIkv2Nm

# Part -2 Python Basics (Conditional Statements)

1) A company decided to give bonus of 5% to employee if his/her year of service is more than 5 years.
Ask user for their salary and year of service and print the net bonus amount.
"""

#Type your code here
salary = float(input("Enter Salary:"))
years = float(input("Enter year of Experience:"))

net_bonus = salary * 0.05 if years >= 5 else 0
print("Net Bonus Amount:",net_bonus)

"""
2) Write a program to check whether a person is eligible for voting or not. (accept age from user) if age is greater than 17 eligible otherwise not eligible"""

from typing import AsyncGenerator
#Type your code here
age = int(input("Enter Age:"))
print("Eligible" if age >= 18 else "Not Eligible")

"""
3) Write a program to check whether a number entered by user is even or odd."""

#Type your code here
num = int(input("Enter Number:"))
print("Even" if num % 2 == 0 else "Odd")

"""4) Write a program to check whether a number is divisible by 7 or not.
Show Answer
"""

#Type your code here
num = int(input("Enter Number:"))
print("Divisible" if num % 7 == 0 else "Not Divisible")

"""5) Write a program to display
"Hello" if a number entered by user is a multiple of five , otherwise print "Bye".
"""

#Type your code here
num = int(input("Enter Number:"))
print("Hello" if num % 5 == 0 else "Bye")

"""7) Write a program to display the last digit of a number.

"""

#Type your code here
num = int(input("Enter Number:"))
print(num % 10)

"""9) Take values of length and breadth of a rectangle from user and print if it is square or rectangle."""

#Type your code here
length = float(input("Enter Length:"))
breadth = float(input("Enter Breadth:"))
print("Square" if length == breadth else "Rectangle")

"""10) Take two int values from user and print greatest among them."""

a = int(input("Enter First Number:"))
b = int(input("Enter Second Number:"))

print(f"Greatest:{a}" if a > b else (f"Greatest:{b}" if b > a else "Both Equal"))

"""11) A shop will give discount of 10% if the cost of purchased quantity is more than 1000.
Ask user for quantity
Suppose, one unit will cost 100.
Judge and print total cost for user.
"""

#Type your code here
qty =int(input("Enter Quantity:"))
cost = qty * 100
discount = cost * 0.1 if cost > 1000 else 0
print("Total Cost:",cost - discount)

"""12) A school has following rules for grading system:

a. Below 25 - F

b. 25 to 45 - E

c. 45 to 50 - D

d. 50 to 60 - C

e. 60 to 80 - B

f. Above 80 - A

Ask user to enter marks and print the corresponding grade.
"""

#Type your code here
marks = int(input("Enter Marks:"))
if marks < 25:
  print("Grade:F")
elif marks >= 25 and marks < 45:
  print("Grade:E")
elif marks >= 45 and marks < 50:
  print("Grade:D")
elif marks >= 50 and marks < 60:
  print("Grade:C")
elif marks >= 60 and marks < 80:
  print("Grade:B")
else:
  print("Grade:A")

"""14)A student will not be allowed to sit in exam if his/her attendence is less than 75%.

Take following input from user

- Number of classes held

- Number of classes attended.

And print

- percentage of class attended

- Is student is allowed to sit in exam or not.

"""

#Type your code here
held = int(input("Enter Number of Classes Held:"))
attended = int(input("Enter Number of Classes Attended:"))
percentage = (attended / held) * 100
print("Percentage of Class Attended:",percentage)
print("Allowed" if percentage >= 75 else "Not Allowed")

"""15) Modify the above question to allow student to sit if he/she has medical cause. Ask user if he/she has medical cause or not ( 'Y' or 'N' ) and print accordingly."""

held = int(input("Enter Number of Classes Held:"))
attended = int(input("Enter Number of Classes Attended:"))
percentage = (attended / held) * 100
print("Percentage of Class Attended:", percentage)

if percentage >= 75:
  print("Is student allowed to sit in exam: Yes")
else:
  medical = input("Do you have a medical cause? ('Y' or 'N'): ").upper()
  if medical == "Y":
    print("Is student allowed to sit in exam: Yes (Medical Exception)")
  else:
    print("Is student allowed to sit in exam: No")

"""16) Write a program to check if a year is leap year or not.

If a year is divisible by 4 then it is leap year but if the year is century year like 2000, 1900, 2100 then it must be divisible by 400.
"""

#Type your code here
year = int(input("Enter Year:"))
if year %4 == 0:
  if year % 100 == 0:
    if year % 400 == 0:
      print("Leap Year")
    else:
      print("Not Leap Year")
  else:
    print("Leap Year")

"""17) Ask user to enter age, gender ( M or F ), marital status ( Y or N ) and then using following rules print their place of service.

if employee is female, then she will work only in urban areas.

if employee is a male and age is in between 20 to 40 then he may work in anywhere

if employee is male and age is in between 40 t0 60 then he will work in urban areas only.

And any other input of age should print "ERROR"
"""

#Type your code here
age = int(input("Enter Age:"))
gender = input("Enter Gender(M/F):")
marital_status = input("Enter Marital Status(Y/N):")

if gender == "F":
  print("Work Only in Urban Areas")
elif gender == "M":
  if age >= 20 and age <= 40:
    print("May Work Anywhere")
    if age >= 40 and age <= 60:
      print("Work Only in Urban Areas")
  else:
    print("ERROR")

"""6) Write a program to calculate the electricity bill (accept number of unit from user) according to the following criteria :
     Unit                                                     Price  
uptp 100 units                                             no charge
Next 200 units                                              Rs 5 per unit
After 200 units                                             Rs 10 per unit
(For example if input unit is 350 than total bill amount is Rs.3500
(For example if input unit is 97 than total bill amount is Rs.0
(For example if input unit is 150 than total bill amount is Rs.750
"""

units = int(input("Enter number of units: " ))
bill = 0

if units <= 100:
    bill = 0
elif units <= 300:
    bill = (units - 100) * 5
else:
    bill = (200 * 5) + (units - 300) * 10

print(f"Total bill amount: Rs.{bill}")

"""13) Take input of age of 3 people by user and determine oldest and youngest

1.   List item
2.   List item

among them.
"""

a = int(input("Enter age 1: "))
b = int(input("Enter age 2: "))
c = int(input("Enter age 3: "))

oldest = max(a, b, c)
youngest = min(a, b, c)

print(f"Oldest: {oldest}, Youngest: {youngest}")

