# -*- coding: utf-8 -*-
"""Assignment03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xHitD_FOY7-cCxfOfoKHeDyx_JODi_U

1. Write a program that accepts a list from user and print the alternate element of list.
"""

user_input = input("Enter a list of elements separated by spaces: ")
user_list = user_input.split()
alternate_elements = user_list[::2]
print("Alternate elements of the list:", alternate_elements)

"""2. Write a program that accepts a list from user. Your program should reverse the content of list and
display it. Do not use reverse() method.

"""

user_input = input("Enter elements separated by space: ")
lst = user_input.split()

reversed_lst = lst[::-1]
print("Reversed list:", reversed_lst)

"""3. Find and display the largest number of a list without using built-in function max(). Your program
should ask the user to input values in list from keyboard.

"""

user_input = input("Enter elements separated by space: ")
lst = [int(x) for x in user_input.split()]

largest = lst[0]
for num in lst:
    if num > largest:
        largest = num

print("The largest number in the list is:", largest)

"""4. Write a program that rotates the element of a list so that the element at the first index moves to the
second index, the element in the second index moves to the third index, etc., and the element in the last
index moves to the first index.
"""

user_input = input("Enter elements separated by space: ")
lst = user_input.split()

if lst:
  rotated = [lst[-1]] + lst[:-1]
  print("Rotated list:", rotated)
else:
  print("List is empty!")

"""5. Write a program that input a string and ask user to delete a given word from a string.

"""

text = input("Enter a string: ")
word = input("Enter the word to delete: ")
new_text = text.replace(word, "")
print("Modified string:", new_text)

"""6. Write a program that reads a string from the user containing a date in the form mm/dd/yyyy. It
should print the date in the form March 12, 2021.
"""

date_str = input("Enter a date (mm/dd/yyyy): ").strip('"\'')

if len(date_str.split('/')) != 3:
    print("Error: Invalid date format. Please use mm/dd/yyyy.")
else:
    month_str, day_str, year_str = date_str.split('/')

    months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

    try:
        month_index = int(month_str) - 1
    except ValueError:
        print(f"Error: Invalid month number '{month_str}'. Month must be a number.")
        month_index = -1 # Indicate an invalid month

    if 0 <= month_index < len(months):
        month = months[month_index]
        day = day_str
        year = year_str
        print(f"{month} {day}, {year}")
    else:
        print(f"Error: Invalid month number '{month_str}'. Please enter a month between 01 and 12.")

"""7. Write a program with a function that accepts a string from keyboard and create a new string after
converting character of each word capitalized. For instance, if the sentence is "stop and smell the roses."
the output should be "Stop And Smell The Roses"
"""

def capitalize_each_words(text):
  words = text.split()
  capitalize_words = [word.capitalize() for word in words]
  return " ".join(capitalize_words)

user_input = input("Enter a string: ")
result = capitalize_each_words(user_input)
print("Modified string:", result)

"""8. Find the sum of each row of matrix of size m x n. For example for the following matrix output will be
like this
"""

matrix = [[2, 11, 7, 12], [5, 2, 9, 15], [8, 3, 10, 42]]

row_sums = []
for row in matrix:
  row_sums.append(sum(row))

print(row_sums)

"""9. Write a program to add two matrices of size n x m.

"""

A = [1,2,3],[4,5,6]
B = [7,8,9],[10,11,12]

n,m = len(A),len(A[0])
result = []

for i in range(n):
  row = []

for j in range(m):
    row.append(A[i][j] + B[i][j])
    result.append(row)
print(result)

"""10. Write a program to multiply two matrices"""

A = [1,2,3],[4,5,6]
B = [[7,8],[9,10],[11,12]]

p = len(A)
q = len(A[0])
r = len(B[0])

result = [[0] * r for _ in range(p)]

for i in range(p):
  for j in range(r):
    for k in range(q):
      result[i][j] += A[i][k] * B[k][j]

print(result)

